import { permissionKeys } from "./permissionCatalog";
import type { DefaultRoleDefinition } from "../types/role.types";

export const defaultRoles: DefaultRoleDefinition[] = [
  {
    id: "admin",
    name: "Administrador",
    description: "Acceso completo al sistema",
    permissions: permissionKeys,
    isSystem: true,
    isAdmin: true,
  },
  {
    id: "dentist",
    name: "Dentista",
    description: "Operación clínica diaria",
    permissions: [
      "dashboard.view",
      "patients.view",
      "patients.create",
      "patients.update",
      "patients.clinicalHistory.view",
      "patients.clinicalHistory.update",
      "patients.odontogram.view",
      "patients.odontogram.update",
      "services.view",
      "quotations.view",
      "quotations.create",
      "quotations.pdf.generate",
      "agenda.view",
      "agenda.doctors.viewOwn",
      "agenda.changes.acknowledge",
      "agenda.notifications.view",
    ],
    isSystem: true,
    isAdmin: false,
  },
  {
    id: "reception",
    name: "Recepción",
    description: "Atención y gestión operativa",
    permissions: [
      "dashboard.view",
      "patients.view",
      "patients.create",
      "patients.update",
      "services.view",
      "quotations.view",
      "quotations.create",
      "quotations.pdf.generate",
      "agenda.view",
      "agenda.doctors.viewAll",
      "agenda.appointments.create",
      "agenda.appointments.update",
      "agenda.appointments.cancel",
      "agenda.notifications.view",
      "sales.view",
      "sales.create",
      "sales.payments.manage",
      "sales.cashShift.open",
      "sales.cashShift.close",
    ],
    isSystem: true,
    isAdmin: false,
  },
];